---
- hosts: all
  vars:
     packages:
       - vim
       - curl
       - wget
       - software-properties-common
       - autofs
       - apt-transport-https
       - ca-certificates
       - docker-ce
       - avahi-daemon
       - libnss-mdns
       - kubeadm
       - kubelet
       - kubectl
       - kubernetes-cni
  tasks:
     - name: Force ipv4 for apt-get
       copy: content="Acquire::ForceIPv4 \"true\";" dest="/etc/apt/apt.conf.d/99force-ipv4"

     - name: Disable unattended upgrades
       lineinfile:
         path: /etc/apt/apt.conf.d/10periodic
         line: "APT::Periodic::Unattended-Upgrade \"0\";"
         state: present
         create: yes

     - name: Add docker apt signing key
       apt_key:
         id: 0EBFCD88
         url: https://download.docker.com/linux/ubuntu/gpg 
         state: present

     - name: Add Google Cloud apt key
       apt_key:
         id: A7317B0F
         url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
         state: present

     - apt_repository:
         repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
         state: present
         filename: 'docker'

     - apt_repository:
         repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
         state: present
         filename: 'kubernetes'

     - name: Update cache
       apt: update_cache=yes cache_valid_time=86400

     - name: Install Packages
       apt: name={{ item }} state=latest
       with_items: "{{ packages }}"

     - name: add search .local to resolver
       lineinfile:
         path: /etc/resolv.conf
         line: search local
         state: present

- hosts: master
  tasks:
    - name: execute kube-init-master.sh
      command: "/vagrant/kube-init-master.sh {{hostvars[inventory_hostname].private_ip}}"
      args:
        creates: /etc/kubernetes/admin.conf
      register: kube-init

- hosts: all:!master
  tasks:
    - name: execute kube-join on slaves
      command: "/vagrant/kube-join-slave.sh"
      args:
        creates: /etc/kubernetes/pki/ca.crt
